stages:
  - test
  - build
  - publish

variables:
  GIT_CLEAN_FLAGS: -ffdx -e vendor/

include:
  - project: 'sevio/gems-ci'
    ref: master
    file: 'default_testing.yml'
  - project: 'sevio/gems-ci'
    ref: master
    file: 'default_build.yml'
  - project: 'sevio/gems-ci'
    ref: master
    file: 'default_publish.yml'
